In [41]:
import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [42]:
df=pd.read_csv('Social_media_impact_on_life.csv')
df

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Overall_Impact
0,232,21,Male,Undergraduate,Other,4.0,Facebook,No,6.7,6.8,Neutral
1,564,23,Female,Undergraduate,Other,1.6,LinkedIn,No,8.6,7.6,Positive
2,788,22,Male,Graduate,Canada,4.6,Instagram,No,6.7,7.0,Neutral
3,686,18,Male,Undergraduate,Other,7.0,Snapchat,Yes,5.4,5.3,Negative
4,608,24,Female,High School,Other,7.5,Facebook,Yes,5.0,4.4,Negative
...,...,...,...,...,...,...,...,...,...,...,...
1700,701,20,Female,Undergraduate,Italy,4.7,TikTok,No,7.2,7.0,Positive
1701,702,23,Male,Graduate,Russia,6.8,Instagram,Yes,5.9,4.0,Negative
1702,703,21,Female,Undergraduate,China,5.6,WeChat,Yes,6.7,6.0,Negative
1703,704,24,Male,Graduate,Japan,4.3,Twitter,No,7.5,8.0,Positive
1704,705,19,Female,Undergraduate,Poland,6.2,Facebook,Yes,6.3,5.0,Negative

In [54]:
print(df.isnull().sum())

Student_ID                      0
Age                             0
Gender                          0
Academic_Level                  0
Country                         0
Avg_Daily_Usage_Hours           0
Most_Used_Platform              0
Affects_Academic_Performance    0
Sleep_Hours_Per_Night           0
Mental_Health_Score             0
Overall_Impact                  0
dtype: int64

In [55]:
print("Columns in dataset:", df.columns)

Columns in dataset: Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Country',
       'Avg_Daily_Usage_Hours', 'Most_Used_Platform',
       'Affects_Academic_Performance', 'Sleep_Hours_Per_Night',
       'Mental_Health_Score', 'Overall_Impact'],
      dtype='object')

In [56]:
df.fillna(0, inplace=True)

In [57]:
print(df.columns)

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Country',
       'Avg_Daily_Usage_Hours', 'Most_Used_Platform',
       'Affects_Academic_Performance', 'Sleep_Hours_Per_Night',
       'Mental_Health_Score', 'Overall_Impact'],
      dtype='object')

In [58]:
print(df.head())

   Student_ID  Age  Gender  Academic_Level  Country  Avg_Daily_Usage_Hours  \
0         232   21       1               2       73                    4.0
1         564   23       0               2       73                    1.6
2         788   22       1               0       18                    4.6
3         686   18       1               2       73                    7.0
4         608   24       0               1       73                    7.5

   Most_Used_Platform  Affects_Academic_Performance  Sleep_Hours_Per_Night  \
0                   0                             0                    6.7
1                   4                             0                    8.6
2                   1                             0                    6.7
3                   5                             1                    5.4
4                   0                             1                    5.0

   Mental_Health_Score  Overall_Impact
0                  6.8               1
1                  7.6               2
2                  7.0               1
3                  5.3               0
4                  4.4               0

In [59]:
x = df.drop("Overall_Impact", axis=1)
y = df["Overall_Impact"]

In [60]:
x

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score
0,232,21,1,2,73,4.0,0,0,6.7,6.8
1,564,23,0,2,73,1.6,4,0,8.6,7.6
2,788,22,1,0,18,4.6,1,0,6.7,7.0
3,686,18,1,2,73,7.0,5,1,5.4,5.3
4,608,24,0,1,73,7.5,0,1,5.0,4.4
...,...,...,...,...,...,...,...,...,...,...
1700,701,20,0,2,44,4.7,6,0,7.2,7.0
1701,702,23,1,0,83,6.8,1,1,5.9,4.0
1702,703,21,0,2,20,5.6,9,1,6.7,6.0
1703,704,24,1,0,46,4.3,7,0,7.5,8.0
1704,705,19,0,2,79,6.2,0,1,6.3,5.0

In [61]:
y

0       1
1       2
2       1
3       0
4       0
       ..
1700    2
1701    0
1702    0
1703    2
1704    0
Name: Overall_Impact, Length: 1705, dtype: int64

In [62]:
encoders = {}
for col in df.select_dtypes(include='object').columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

In [63]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [64]:
# Train model
model = RandomForestClassifier()
model.fit(x_train, y_train)

RandomForestClassifier()

In [67]:

y_pred = model.predict(x_test)
y_pred

array([0, 2, 0, 2, 0, 0, 2, 0, 0, 0, 2, 1, 1, 1, 0, 0, 1, 0, 0, 0, 2, 0,
       0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 1, 0, 1, 2, 0, 0, 0, 0, 1, 0, 2,
       2, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 2, 0, 2, 1, 1, 2, 1, 0, 2,
       2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 2, 0, 2, 0, 0, 2, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2,
       0, 0, 1, 0, 0, 2, 0, 2, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 2, 0, 1, 2, 1, 0, 2, 0, 0, 2, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 1, 2, 0, 1, 0, 0, 0,
       1, 0, 2, 0, 2, 2, 1, 2, 1, 2, 2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 1, 0,
       2, 2, 0, 0, 1, 2, 0, 1, 2, 0, 2, 1, 0, 2, 0, 0, 0, 2, 0, 1, 0, 2,
       0, 1, 1, 2, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 0, 1, 2, 2, 2, 2, 0, 0,
       1, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 1, 2, 2, 0, 1, 2, 0, 0, 0, 1, 1,
       0, 2, 0, 0, 1, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0,
       0, 2, 0, 1, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 0, 0, 0, 2, 0, 1, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 2, 2, 2,
       0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0])

In [68]:
# ✅ Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

Model Accuracy: 0.9912023460410557